apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    chart: external-secrets
    targetRevision: 0.10.3
    helm:
      releaseName: external-secrets
      values: |
        certController:
          resources:
            limits:
              cpu: "10m"
              memory: "50Mi"
            requests:
              cpu: "1m"
              memory: "37Mi"
        webhook:
          resources:
            limits:
              cpu: "10m"
              memory: "50Mi"
            requests:
              cpu: "1m"
              memory: "24Mi"
        resources:
          limits:
            cpu: "10m"
            memory: "40Mi"
          requests:
            cpu: "2m"
            memory: "23Mi"
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true