apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konga-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/pantsel/konga'
    targetRevision: HEAD
    path: 'charts/konga'
    helm:
      values: |
        resources:
          requests:
            cpu: 197m
            memory: 149Mi
  destination:
    namespace: tool-authorization
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
