apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 16.3.0
    helm:
      releaseName: mongodb
      values: |
        architecture: replicaset
        auth:
          enabled: true
          existingSecret: mongodb-mongodb
        persistence:
          size: 30Gi
  destination:
    namespace: tool-database
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
