apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: sonarqube
    targetRevision: 15.0.4
    helm:
      releaseName: sonarqube
      values: |
        postgresql:
          enabled: false
          auth:
            username: sonar
            password: sonarpassword
            database: sonarqube
        service:
          type: ClusterIP
#        resources:
#          requests:
#            memory: 2Gi
#            cpu: 1
#          limits:
#            memory: 4Gi
#            cpu: 2
  destination:
    namespace: sonarqube
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
