apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 5.2.0
    helm:
      releaseName: sonarqube
      values: |
        postgresql:
          enabled: false
          postgresqlUsername: sonar
          postgresqlPassword: sonarpassword
          postgresqlDatabase: sonarqube
        service:
          type: ClusterIP
  destination:
    namespace: sonarqube
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
